pipeline {
    agent any
    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }
        stage('Run Tests') {
            steps {
                sh 'cd Selenium/Task3 && xvfb-run --auto-servernum python3 Task3.py'
            }
        }
    }
}
