pipeline {
    agent any
    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }
        stage('Run Tests') {
            steps {
                // Change directory to "Selenium/Task 3" and run Task3.py
                sh 'cd Selenium/Task3 && python3 Task3.py'
            }
        }
    }
}
